name: tarballs

on:
  release: null
  push:
    tags: ['*']

jobs:
  upload:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, system: x86_64-linux }
          - { os: macos-latest, system: x86_64-darwin }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCS_PROJECT }}

      - run: nix-build -A tarball --arg enableStatic true

      - name: Run upload to bootstrap.urbit.org
        run: |
          version="$(cat ./pkg/urbit/version)"
          system="$(nix-instantiate --eval --expr 'builtins.currentSystem')"
          system=${system:1:${#system}-2}
          target="gs://bootstrap.urbit.org/ci/urbit-v${version}-${system}-${GITHUB_SHA:0:9}.tgz"

          gsutil cp -n ./result "$target"

          echo "upload to $target complete."
